### ISSUE TITLE
Error After Compiling App

### ISSUE THREAD

**Issue by roboflank** [sbolel/image-uploader#1]
Hello,

Great plugin :+1:
`Uncaught SyntaxError: Use of const in strict mode. image-uploader.js:3`
`ReferenceError: ImageUploader is not defined`

This error appears once i compile the app. But on browser it seems to work fine

**Comment by roboflank** [comment]
Here is the screenshot
![screenshot from 2016-09-04 14 24 52](https://cloud.githubusercontent.com/assets/6532631/18230664/a1ccd998-72ab-11e6-9de4-ed0078c506dc.png)

**Comment by sbolel** [comment]
Hi, thanks for reporting this. Fixed by #2

**Comment by sbolel** [comment]
Hi, thanks for reporting this. Fixed in PR #2

**Comment by roboflank** [comment]
Thanks :)
Let me try now.
