### ISSUE TITLE
Warnings on install, and at Vercel

### ISSUE THREAD

**Issue by sarahk** [sbolel/image-uploader#12]
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: 'image-uploader@2.0.2',
npm WARN EBADENGINE   required: { node: '^12.0.0', npm: '^7.0.0' },
npm WARN EBADENGINE   current: { node: 'v16.13.1', npm: '8.3.0' }
npm WARN EBADENGINE }

how important are these warnings?

**Comment by sbolel** [comment]
This repo is no longer maintained.

**Comment by sbolel** [comment]
Closing since this repo is no longer maintained.
